### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by zImPinguin** [Hadi-koubeissi/ManageGift#30]
TypeError: Cannot read property 'send' of undefined
    at module.exports (C:\Users\Admin\Desktop\südpolgiveaways\events\message.js:43:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
C:\Users\Admin\Desktop\südpolgiveaways\index.js:22
setInterval(() => something.word(message), 10000);
                            
                            How i can fix?

**Comment by Hadi-koubeissi** [comment]
thx i will fix this in the next update soon

**Comment by Hadi-koubeissi** [comment]
but this error because you dont set id of command log in config.js
