### ISSUE TITLE
Dasboard

### ISSUE THREAD

**Issue by brblacky** [Hadi-koubeissi/ManageGift#32]
@Hadi-koubeissi  Are you Adding Dasboard in ManageGift Bot ?

**Comment by LWJerri** [comment]
> @Hadi-koubeissi  Are you Adding Dasboard in ManageGift Bot ?

Hello. Currently bot don't have web dashboard.

**Comment by brblacky** [comment]
But Developer add maybe in future

**Comment by Hadi-koubeissi** [comment]
yes yes in the future
