### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by brblacky** [Hadi-koubeissi/ManageGift#33]
Please tell me how can i remove guild blacklist bot in not reply in my Server

**Comment by Hadi-koubeissi** [comment]
What appears to you in the console. in this release you cannot remove the server from the blacklist by using a command. You must enter the database and delete all server settings to start again

**Comment by brblacky** [comment]
I am delete in mongodb using guild id  but it is still not reply

**Comment by Hadi-koubeissi** [comment]
Well if the problem is not in the blacklist, what do you see in the console?

**Comment by brblacky** [comment]
It is something can't not read 'send' in message.js

**Comment by Hadi-koubeissi** [comment]
Ahaaaaaa yep you need to add command channel log id in the config and his work 100%

**Comment by brblacky** [comment]
Yes log is working in working guild

**Comment by brblacky** [comment]
Can you please update with blacklist guild removing cmd
