### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by Fantom-XR** [Hadi-koubeissi/ManageGift#38]
![image](https://user-images.githubusercontent.com/52836243/152814582-ad508870-b7c5-4360-9726-5d24367e57be.png)

**Comment by Hadi-koubeissi** [comment]
Discord.js version? And discord-giveaways version 🤔

**Comment by Fantom-XR** [comment]
> Discord.js version? And discord-giveaways version 🤔

Discord.js version is v12.22.6

**Comment by Fantom-XR** [comment]
> discord-giveaways version ??...

I did npm i discord-giveaways so i'm guessing 5.1.1 as stated on https://www.npmjs.com/package/discord-giveaways

**Comment by Hadi-koubeissi** [comment]
Because of that, it doesn't work because this version of the bot runs on the discord-giveaways version found in the package.json file.
